### 1、逻辑运算

In [2]:
import numpy as np
stock_change = np.random.normal(loc=0, scale=1, size=(8, 10))

In [2]:
stock_change

array([[ 0.64326146, -1.41741155, -0.03213892,  0.71792731,  0.79948875,
         0.70224627,  0.69442911,  1.79047143,  0.71805163,  1.07876756],
       [-1.68239285, -0.73154805,  0.06769326,  0.20615696,  0.85701273,
         0.58917519,  1.01472065, -0.33339509, -0.72443531, -0.34289181],
       [ 0.19333838, -0.39109997, -0.67482769, -0.58956485, -0.66588434,
        -0.80283959,  3.36766507, -1.47611793,  0.40845955, -1.27006384],
       [-0.01936531, -0.54125946, -0.33467765,  0.75418895,  0.66800866,
         0.06769091, -0.49305072,  1.49228884,  0.02114607, -0.54552951],
       [ 1.19971121, -1.23858538, -1.06340256,  1.08664779, -0.20119848,
         0.32809328,  2.01757618,  1.35305609,  0.79449169,  0.81734081],
       [-0.3484097 ,  0.78634999, -1.5702257 ,  0.72775156, -1.94546175,
         0.85475762,  1.72788577,  1.21950218, -1.42042402, -0.18696216],
       [-0.87387662, -1.11261149, -0.48101959, -0.43128963, -0.72088993,
        -0.98866675, -2.37122552,  0.62829974

In [3]:
# 逻辑判断
stock_change > 0.5

array([[ True, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False,  True,  True,  True, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False,  True,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True,  True,  True,
         True],
       [False,  True, False,  True, False,  True,  True,  True, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False]])

In [5]:
# 布尔索引
stock_change[stock_change > 0.5]

array([0.64326146, 0.71792731, 0.79948875, 0.70224627, 0.69442911,
       1.79047143, 0.71805163, 1.07876756, 0.85701273, 0.58917519,
       1.01472065, 3.36766507, 0.75418895, 0.66800866, 1.49228884,
       1.19971121, 1.08664779, 2.01757618, 1.35305609, 0.79449169,
       0.81734081, 0.78634999, 0.72775156, 0.85475762, 1.72788577,
       1.21950218, 0.62829974, 1.07173287, 1.058413  ])

In [6]:
stock_change[stock_change > 0.5] = 1

In [8]:
stock_change

array([[ 1.        , -1.41741155, -0.03213892,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [-1.68239285, -0.73154805,  0.06769326,  0.20615696,  1.        ,
         1.        ,  1.        , -0.33339509, -0.72443531, -0.34289181],
       [ 0.19333838, -0.39109997, -0.67482769, -0.58956485, -0.66588434,
        -0.80283959,  1.        , -1.47611793,  0.40845955, -1.27006384],
       [-0.01936531, -0.54125946, -0.33467765,  1.        ,  1.        ,
         0.06769091, -0.49305072,  1.        ,  0.02114607, -0.54552951],
       [ 1.        , -1.23858538, -1.06340256,  1.        , -0.20119848,
         0.32809328,  1.        ,  1.        ,  1.        ,  1.        ],
       [-0.3484097 ,  1.        , -1.5702257 ,  1.        , -1.94546175,
         1.        ,  1.        ,  1.        , -1.42042402, -0.18696216],
       [-0.87387662, -1.11261149, -0.48101959, -0.43128963, -0.72088993,
        -0.98866675, -2.37122552,  1.        

In [9]:
stock_change[0:2][0:5] > 0

array([[ True, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [False, False,  True,  True,  True,  True,  True, False, False,
        False]])

In [10]:
# 通用判断函数
np.all(stock_change[0:2][0:5] > 0)  # 全为True才返回True

False

In [11]:
np.any(stock_change[0:2][0:5] > 0)  # 有1个为True就返回True

True

In [14]:
# 三元运算符
# np.where(布尔值，True的位置的值，False的位置的值)
temp = stock_change[:4, :4]

In [15]:
temp

array([[ 1.        , -1.41741155, -0.03213892,  1.        ],
       [-1.68239285, -0.73154805,  0.06769326,  0.20615696],
       [ 0.19333838, -0.39109997, -0.67482769, -0.58956485],
       [-0.01936531, -0.54125946, -0.33467765,  1.        ]])

In [17]:
temp > 0

array([[ True, False, False,  True],
       [False, False,  True,  True],
       [ True, False, False, False],
       [False, False, False,  True]])

In [18]:
np.where(temp > 0, 1, 0)

array([[1, 0, 0, 1],
       [0, 0, 1, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1]])

In [20]:
# 复合逻辑
np.logical_and(temp > 0.5, temp < 1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [21]:
np.where(np.logical_and(temp > 0.5, temp < 1), 1, 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.logical_or(temp > 0.5, temp < -0.5)

array([[ True,  True, False,  True],
       [ True,  True, False, False],
       [False, False,  True,  True],
       [False,  True, False,  True]])

In [24]:
np.where(np.logical_or(temp > 0.5, temp < -0.5), 1, 0)

array([[1, 1, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 1]])

### 2、统计运算

In [25]:
temp

array([[ 1.        , -1.41741155, -0.03213892,  1.        ],
       [-1.68239285, -0.73154805,  0.06769326,  0.20615696],
       [ 0.19333838, -0.39109997, -0.67482769, -0.58956485],
       [-0.01936531, -0.54125946, -0.33467765,  1.        ]])

In [29]:
temp.max(axis=0)  # 每一列的最大值

array([ 1.        , -0.39109997,  0.06769326,  1.        ])

In [34]:
np.min(temp, axis=1)  # 每一行的最小值

array([-1.41741155, -1.68239285, -0.67482769, -0.54125946])

In [35]:
np.argmax(temp, axis=0)

array([0, 2, 1, 0], dtype=int64)

In [36]:
np.argmin(temp, axis=1)

array([1, 0, 2, 1], dtype=int64)

### 3、数组间运算

In [37]:
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])

In [38]:
arr

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [39]:
# 数组与数字的运算
arr + 1

array([[2, 3, 4, 3, 2, 5],
       [6, 7, 2, 3, 4, 2]])

In [40]:
arr / 2

array([[0.5, 1. , 1.5, 1. , 0.5, 2. ],
       [2.5, 3. , 0.5, 1. , 1.5, 0.5]])

In [41]:
# 数组间的运算
# broadcast机制：同维度下的元素数目相等 or 存在1
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

arr1.shape

In [43]:
arr2.shape

(2, 1)

In [44]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

In [45]:
arr1 * arr2

array([[ 1,  2,  3,  2,  1,  4],
       [15, 18,  3,  6,  9,  3]])

In [46]:
arr1 / arr2

array([[1.        , 2.        , 3.        , 2.        , 1.        ,
        4.        ],
       [1.66666667, 2.        , 0.33333333, 0.66666667, 1.        ,
        0.33333333]])

### 4、矩阵运算

In [3]:
# ndarray存储矩阵
data = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [4]:
data

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [5]:
# matrix存储矩阵
data_mat = np.mat([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [6]:
data_mat  # (8, 2)

matrix([[80, 86],
        [82, 80],
        [85, 78],
        [90, 90],
        [86, 82],
        [82, 90],
        [78, 80],
        [92, 94]])

In [8]:
weights = np.array([[0.3], [0.7]])  # (2, 1)

In [9]:
weights

array([[0.3],
       [0.7]])

In [13]:
weights_mat = np.mat([[0.3], [0.7]])

In [10]:
# 矩阵（二维数组）运算
np.matmul(data, weights)  # (8, 2) * (2, 1) = (8, 1)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [11]:
np.dot(data, weights)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [15]:
data @ weights

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [14]:
# 矩阵运算
data_mat * weights_mat

matrix([[84.2],
        [80.6],
        [80.1],
        [90. ],
        [83.2],
        [87.6],
        [79.4],
        [93.4]])

### 5、合并、分割

In [16]:
a = stock_change[:2, 0:4]
b = stock_change[4:6, 0:4]

In [17]:
a

array([[-0.50416139,  0.25727289,  0.25294282, -0.85622214],
       [ 0.8311718 ,  0.27925339, -0.14132699, -0.80335951]])

In [18]:
b

array([[-1.10253645,  0.11667327,  0.49389823,  0.26543307],
       [-0.67725844,  0.29449182,  0.3321434 ,  0.58058302]])

In [20]:
# 水平拼接
np.hstack((a, b))

array([[-0.50416139,  0.25727289,  0.25294282, -0.85622214, -1.10253645,
         0.11667327,  0.49389823,  0.26543307],
       [ 0.8311718 ,  0.27925339, -0.14132699, -0.80335951, -0.67725844,
         0.29449182,  0.3321434 ,  0.58058302]])

In [21]:
np.concatenate((a, b), axis=1)

array([[-0.50416139,  0.25727289,  0.25294282, -0.85622214, -1.10253645,
         0.11667327,  0.49389823,  0.26543307],
       [ 0.8311718 ,  0.27925339, -0.14132699, -0.80335951, -0.67725844,
         0.29449182,  0.3321434 ,  0.58058302]])

In [22]:
# 竖直拼接
np.vstack((a, b))

array([[-0.50416139,  0.25727289,  0.25294282, -0.85622214],
       [ 0.8311718 ,  0.27925339, -0.14132699, -0.80335951],
       [-1.10253645,  0.11667327,  0.49389823,  0.26543307],
       [-0.67725844,  0.29449182,  0.3321434 ,  0.58058302]])

In [23]:
np.concatenate((a, b), axis=0)

array([[-0.50416139,  0.25727289,  0.25294282, -0.85622214],
       [ 0.8311718 ,  0.27925339, -0.14132699, -0.80335951],
       [-1.10253645,  0.11667327,  0.49389823,  0.26543307],
       [-0.67725844,  0.29449182,  0.3321434 ,  0.58058302]])

In [24]:
# 分割
x = np.arange(9.0)

In [25]:
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [27]:
np.split(x, 3)  # 将x分为3份

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [29]:
np.split(x, [3, 5, 6, 9])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7., 8.]),
 array([], dtype=float64)]

### 6、IO操作与数据处理

In [33]:
# 读取数据
data = np.genfromtxt("test.csv", delimiter=",")

In [34]:
data  # 一般不用numpy读取数据

array([[  nan,   nan,   nan,   nan],
       [  1. , 123. ,   1.4,  23. ],
       [  2. , 110. ,   nan,  18. ],
       [  3. ,   nan,   2.1,  19. ]])

In [35]:
# 处理缺失值
def fill_nan_by_column_mean(t):
    for i in range(t.shape[1]):
        # 计算nan的个数
        nan_num = np.count_nonzero(t[:, i][t[:, i] != t[:, i]])
        if nan_num > 0:
            now_col = t[:, i]
            # 求和
            now_col_not_nan = now_col[np.isnan(now_col) == False].sum()
            # 和/个数
            now_col_mean = now_col_not_nan / (t.shape[0] - nan_num)
            # 赋值给now_col
            now_col[np.isnan(now_col)] = now_col_mean
            # 赋值给t，即更新t的当前列
            t[:, i] = now_col
    return t

In [38]:
fill_nan_by_column_mean(data)

array([[  2.  , 116.5 ,   1.75,  20.  ],
       [  1.  , 123.  ,   1.4 ,  23.  ],
       [  2.  , 110.  ,   1.75,  18.  ],
       [  3.  , 116.5 ,   2.1 ,  19.  ]])